databases:
  - name: shelter-db
    databaseName: shelter
    user: shelter_user

services:
  - type: web
    name: smart-shelter
    env: docker
    plan: free
    dockerfilePath: ./app/Dockerfile
    dockerContext: ./app
    healthCheckPath: /
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shelter-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0